name: "Copy App Between Environments"
on:
  workflow_dispatch:
    inputs:
      appName:
        description: 'App Base Name'
        required: true
        type: choice
        options:
        - 'MyApp'
        - 'YourApp'
      fromEnv:
        description: 'Source Environment'
        required: true
        default: 'Dev'
        type: choice
        options:
        - Dev
        - Staging
        - Sandbox
      toEnv:
        description: 'Target Environment'
        required: true
        type: choice
        options:
        - Staging
        - Sandbox
        - Production
permissions:
  contents: write
  pull-requests: write
jobs:
  copy-app-codebase:
    env:
      SOURCE_PATH: apps/${{ inputs.appName }}/${{ inputs.appName }}_${{ inputs.fromEnv }}
      TARGET_PATH: apps/${{ inputs.appName }}/${{ inputs.appName }}${{ inputs.toEnv != 'Production' && '_' || '' }}${{ inputs.toEnv != 'Production' && inputs.toEnv || '' }}
    runs-on: ubuntu-latest
    steps:
      # Get date pieces as outputs
      - id: date
        run: |
          echo "::set-output name=year::$(date +'%Y')"
          echo "::set-output name=month::$(date +'%m')"
          echo "::set-output name=day::$(date +'%d')"
          echo "::set-output name=second::$(date +'%s')"
      # Assemble them into a semver-style tag for later use
      - id: tag
        run: |
          echo "::set-output name=tag::${{ format('{0}.{1}.{2}.{3}', steps.date.outputs.year, steps.date.outputs.month, steps.date.outputs.day, steps.date.outputs.second) }}"

      # checkout current main branch
      - uses: actions/checkout@v3

      # Remove target app entirely
      - name: Copy app files from source to target env
        run: rm -rf ./${{ env.TARGET_PATH }}

      # Copy entire app from source to target
      - name: Copy app files from source to target env
        run: cp -a ./${{ env.SOURCE_PATH }} ./${{ env.TARGET_PATH }}

      # Roll changes into a new pull request
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: '[create-pull-request] Copied ${{ inputs.appName }} from ${{ inputs.fromEnv }} to ${{ inputs.toEnv }}'
          branch: create-pull-request/${{ inputs.appName }}/${{ inputs.fromEnv }}-${{ inputs.toEnv }}
          delete-branch: true
          base: main
          title: '[Auto] Copy of "${{ inputs.appName }}" from ${{ inputs.fromEnv }} to ${{ inputs.toEnv }}'
          body: |
            Automated copy of application `${{ inputs.appName }}`

            > Initiated by ${{ github.actor }}

            - From source environment of "${{ inputs.fromEnv }}", in path `${{ env.SOURCE_PATH }}`
            - To target environment of "${{ inputs.toEnv }}", in path `${{ env.TARGET_PATH }}`
            - Tagged as `${{ steps.tag.outputs.tag }}`

      # Tag with the commit sha (maybe something more useful later)
      # - name: Tag Generated Commit
      #   run: |
      #     git tag ${{ steps.tag.outputs.tag }}
      #     git push origin ${{ steps.tag.outputs.tag }}