name: "Copy App Between Environments"
on:
  workflow_dispatch:
    inputs:
      appName:
        description: 'App Base Name'
        required: true
        type: choice
        options:
        - 'MyApp'
        - 'YourApp'
      fromEnv:
        description: 'Source Environment'
        required: true
        default: 'Dev'
        type: choice
        options:
        - 'Dev'
        - 'Staging'
        - 'Sandbox'
      toEnv:
        description: 'Target Environment'
        required: true
        type: choice
        options:
        - 'Staging'
        - 'Sandbox'
        - 'Prod'
permissions:
  contents: write
  pull-requests: write
jobs:
  copy-app-codebase:
    env:
      SOURCE_PATH: apps/${{ inputs.appName }}/${{ inputs.appName }}_${{ inputs.fromEnv }}
      TARGET_PATH: apps/${{ inputs.appName }}/${{ inputs.appName }}${{ inputs.toEnv == 'Prod' && '' || '_' }}${{ inputs.toEnv == 'Prod' && '' || inputs.toEnv }}
    runs-on: ubuntu-latest
    steps:
      # checkout current main branch
      - uses: actions/checkout@v3

      # Remove target app entirely
      - name: Copy app files from source to target env
        run: rm -rf ./${{ env.TARGET_PATH }}

      # Copy entire app from source to target
      - name: Copy app files from source to target env
        run: cp -a ./${{ env.SOURCE_PATH }} ./${{ env.TARGET_PATH }}

      # Roll changes into a new pull request
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: '[create-pull-request] Copied ${{ inputs.appName }} from ${{ inputs.fromEnv }} to ${{ inputs.toEnv }}'
          branch: create-pull-request/${{ inputs.appName }}--${{ inputs.fromEnv }}-${{ inputs.toEnv }}
          delete-branch: true
        #   branch-suffix: random | timestamp | short-commit-hash
        #   base: main
          title: '[Automated] Copying ${{ inputs.appName }} from ${{ inputs.fromEnv }} to ${{ inputs.toEnv }}'
        #   body: Automated changes by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action
